// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDan341Hh5cS9RD3llo590WDPEoV3OwL2w',
    appId: '1:508064861531:web:3d6a1c4636b7d0cd3e9e7e',
    messagingSenderId: '508064861531',
    projectId: 'projetdev-3d53d',
    authDomain: 'projetdev-3d53d.firebaseapp.com',
    storageBucket: 'projetdev-3d53d.firebasestorage.app',
    measurementId: 'G-M7182YHKB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCom-8ccm2CHD0buDgiiSYjMHB5E1FW43E',
    appId: '1:508064861531:android:3d0a79c2e5d5fa1b3e9e7e',
    messagingSenderId: '508064861531',
    projectId: 'projetdev-3d53d',
    storageBucket: 'projetdev-3d53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPh_GmfiDzXs4u5TWyUThP-s-2MiSo7-Y',
    appId: '1:508064861531:ios:3b9a55281980a40b3e9e7e',
    messagingSenderId: '508064861531',
    projectId: 'projetdev-3d53d',
    storageBucket: 'projetdev-3d53d.firebasestorage.app',
    iosBundleId: 'com.example.projetdev.projetDevFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPh_GmfiDzXs4u5TWyUThP-s-2MiSo7-Y',
    appId: '1:508064861531:ios:3b9a55281980a40b3e9e7e',
    messagingSenderId: '508064861531',
    projectId: 'projetdev-3d53d',
    storageBucket: 'projetdev-3d53d.firebasestorage.app',
    iosBundleId: 'com.example.projetdev.projetDevFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDan341Hh5cS9RD3llo590WDPEoV3OwL2w',
    appId: '1:508064861531:web:eecd834dd28be1c93e9e7e',
    messagingSenderId: '508064861531',
    projectId: 'projetdev-3d53d',
    authDomain: 'projetdev-3d53d.firebaseapp.com',
    storageBucket: 'projetdev-3d53d.firebasestorage.app',
    measurementId: 'G-CFKSJN9KYK',
  );

}